import LocalizedStrings from 'react-native-localization'
export default strings = new LocalizedStrings({
    en: {
        welcome_to: 'Welcome to',
        saralData_text: 'SaralData',
        gujarat_text: 'Gujarat',
        provide_details_to_start_scanning_marksheets: 'Provide your details to \nstart scanning the mark sheets',
        proceed: 'PROCEED',
        enter_your_details: 'Enter your details',
        cancel_text_caps: 'CANCEL',
        cancel_text: 'Cancel',
        ok_text: 'Ok',
        enter_your_full_name: 'Enter your full name',
        full_name: 'Full name',
        your_state: 'Your state',
        select_text: 'Select',
        select_district: 'Select district',
        select_block: 'Select block',
        select_cluster: 'Select cluster',
        select_school: 'Select school',
        submit_text: 'SUBMIT',
        my_scans: 'My Scans',
        note_only_last_15_scans_available: 'Note: Only last 15 scans will be available.',
        scan_the_marksheet: 'Scan The Mark Sheet',
        my_profile: 'My Profile',
        class_text: 'Class',
        roll_no: 'Roll No.',
        student_id: 'Student ID',
        booklet_id: 'Booklet ID',
        test_id: 'Test ID',
        test_date: 'Test Date',
        subject_text: 'Subject',
        added_text: 'Added at',
        capture: 'Capture',
        next_text: 'Next',
        re_capture: 'Re-Capture',
        adjust_the_picture: 'Adjust the picture',
        no_content_available_in_page: 'No Content is available in page',
        please_capture_in_portrait_mode: 'Please capture in portrait mode.',
        permisssion_to_use_camera: 'Permission to use camera',
        we_need_permission_to_use_camera: 'We need your permission to use your camera',
        permission_deny: 'Permission Deny',
        you_have_no_permission_to_change_settings: 'You have no permission to change settings',
        open_settings: 'Open Settings',
        process_failed_try_again: 'Process failed, Please try again.',
        message_text: 'Message',
        uploading_image: 'Uploading image...',
        please_wait_while_we_scan_pic: 'Please wait, while we scan the picture',
        scanning_complete: 'Scanning complete!',
        verify_scanned_data: 'Verify scanned data',
        edit_scanned_data: 'Edit scanned data',
        complete_these_steps_submit_marks: 'Complete these steps to submit marks',
        verify_subject_details: 'Verify Subject Details',
        verify_marks_subject: 'Verify Marks & Subject',
        edit_text: 'Edit',
        save_text: 'Save',
        student_details: 'Student Details',
        marks_text: 'Marks',
        table_image_is_not_proper: 'Table image is not proper. Please try again.',
        please_correct_student_id: 'Please correct the Student Id',
        please_correct_exam_id: 'Please correct the Exam Id',
        district_list_error: 'Unable to fetch district list. Please try again.',
        block_list_error: 'Unable to fetch block list. Please select again district.',
        cluster_list_error: 'Unable to fetch cluster list. Please select again block.',
        school_list_error: 'Unable to fetch school list. Please select again cluster.',
        techer_list_error: 'Unable to fetch teachers list. Please select again school.',
        please_select_district: 'Please select district',
        please_select_block: 'Please select block',
        please_select_cluster: 'Please select cluster',
        please_select_school: 'Please select school',
        please_select_test_id: 'Please select test id',
        please_enter_name: 'Please enter full name',
        please_enter_correct_name: 'Please enter correct name',
        examcode_list_error: 'Unable to fetch test id list. Please try again.',
        saved_successfully: 'Saved Successfully',
        please_try_again: 'Please try again.',
        please_correct_marks_data: 'Please edit and correct marks data.',
        change_profile: 'Change Profile',
        summary_scanned_data: 'Scanned data summary',
        total_marks: 'Total Marks',
        total_marks_secured: 'Total marks secured',
        please_correct_test_date: 'Please enter valid date',
        summary_text: 'Summary',
        no_exam_for_given_date: 'No tests for given Date',
        login_text: 'Login',
        enter_username: 'Enter your username',
        username_text: 'Username',
        enter_password: 'Enter your password',
        password_text: 'Password',
        please_enter_username: 'Please enter username',
        please_enter_password: 'Please enter password',
        please_enter_valid_username: 'Invalid username',
        please_enter_valid_password: 'Invalid password',
        username_or_password_doesnot_match: `Username or password doesn't match`,
        username_or_password_doesnot_exists: `Username or password doesn't exist`,
        logout_text: 'Logout',
        select_student_name: 'Select Student Name',
        select_student_id: 'Select Student ID',
        multiple_students_found_for_given_student_id: 'Multiple students found for given Student ID',
        please_select_one_for_which_you_are_scanning: 'Please select student aadhaar number for which you are scanning' ,
        retry_text: 'Retry',
        you_will_loose_all_your_data: 'You will loose all your unsaved scan if any. Are you sure you want to logout?',
        save_scan: 'Save All Scan',
        continue_scan: 'Continue Scan',
        save_status: 'Save Status',
        scan_status: 'Scan Status',
        exam_date: 'Exam Date',
        completed: 'Completed',
        completed_scan: 'Completed Scan',
        ongoing_scan: 'Ongoing Scan',
        current_scan: 'Current Scan',
        no_scan_data_available: 'No Scan Data Available',
        please_give_permission_to_use_app: 'Please give permission to use app',
        permission_text: 'Permission',
        app_needs_permission: 'SaralData app needs access to your camera and storage',
        section: 'Section',
        all_scanned_data_updated: 'All scanned data has been already saved',
        school_name: 'School Name',
        dise_code: 'DISE Code',
        request_timeout_custom_message : "Request timed out. Please check your internet connection and retry.",
        you_seem_to_be_offline_please_check_your_internet_connection: 'Please check your internet connection.',
        saved_text: 'Saved',
        not_saved_text: 'Not Saved',
        go_to_dashboard: 'Go back to Dashboard',
        yes_text: 'Yes',
        no_text: 'No',
        version_text: 'Version',
        test_sub_date: 'Test Subject - Date',
        give_permission_from_settings: 'Please give permission from Settings to use app',
        optional_update_available: 'A new update is available of App. Do you want to update now?',
        force_update_available: 'We have an updated version for you. Please Update to continue using App.',
        no_btn_text: 'No',
        yes_btn_text: 'Yes',
        sat_string: 'SAT',
        pat_string: 'PAT'
    }
})